# Generated by Django 5.0.6 on 2024-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0002_vacation_contacts_vacation_location_vacation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='experience',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
