# Generated by Django 5.0.6 on 2024-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0003_vacation_experience_vacation_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='contacts',
            new_name='contacts2',
        ),
        migrations.AddField(
            model_name='vacation',
            name='contacts1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
