# Generated by Django 5.0.6 on 2024-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0004_rename_contacts_vacation_contacts2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='contacts1',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='contacts2',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
