# Generated by Django 5.0.6 on 2024-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0005_alter_vacation_contacts1_alter_vacation_contacts2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='salary',
            field=models.CharField(max_length=20),
        ),
    ]
