# Generated by Django 5.0.6 on 2024-06-07 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0006_alter_vacation_image_alter_vacation_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacation',
            old_name='description',
            new_name='amenities_ru',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='location',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='image',
            new_name='image_ru',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='name',
            new_name='location_ru',
        ),
        migrations.AddField(
            model_name='vacation',
            name='amenities_uz',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='vacation',
            name='location_uz',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='name_ru',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='name_uz',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='requirements_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='requirements_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacation',
            name='contacts1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='contacts2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
