# Generated by Django 5.0.6 on 2024-06-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0007_rename_description_vacation_amenities_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacation',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterModelOptions(
            name='vacationtype',
            options={'verbose_name': 'Vacancy Type', 'verbose_name_plural': 'Vacancy Types'},
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1_uz', models.TextField()),
                ('test2_uz', models.TextField()),
                ('test3_uz', models.TextField()),
                ('test4_uz', models.TextField(blank=True, null=True)),
                ('test5_uz', models.TextField(blank=True, null=True)),
                ('test1_ru', models.TextField()),
                ('test2_ru', models.TextField()),
                ('test3_ru', models.TextField()),
                ('test4_ru', models.TextField(blank=True, null=True)),
                ('test5_ru', models.TextField(blank=True, null=True)),
                ('vacancy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_vacations.vacationtype')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'test',
            },
        ),
    ]
