# Generated by Django 5.0.6 on 2024-06-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0009_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer1',
            new_name='answer_ru',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='answer2',
            new_name='answer_uz',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test1_ru',
            new_name='test_ru',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test1_uz',
            new_name='test_uz',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer3',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer4',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer5',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test2_ru',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test2_uz',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test3_ru',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test3_uz',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test4_ru',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test4_uz',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test5_ru',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test5_uz',
        ),
    ]
