# Generated by Django 5.0.6 on 2024-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0010_rename_answer1_answers_answer_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
