# Generated by Django 5.0.6 on 2024-06-09 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0011_alter_answers_answer_ru_alter_answers_answer_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='answer_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='answer_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_vacations.test'),
            preserve_default=False,
        ),
    ]
