# Generated by Django 5.0.6 on 2024-06-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0012_users_answer_ru_users_answer_uz_users_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_vacations.test'),
        ),
    ]
