# Generated by Django 5.0.6 on 2024-06-10 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0013_alter_users_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
            ],
            options={
                'verbose_name': 'Budget',
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description1', models.TextField()),
                ('amount2', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('amount3', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('amount4', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description4', models.TextField(blank=True, null=True)),
                ('amount5', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('description5', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
            },
        ),
    ]
