# Generated by Django 5.0.6 on 2024-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0014_budget_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
