# Generated by Django 5.0.6 on 2024-06-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0015_expenses_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vacancy Count',
                'verbose_name_plural': 'Vacancies Count',
                'db_table': 'vacancy_count',
            },
        ),
    ]
