# Generated by Django 5.0.6 on 2024-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vacations', '0016_vacancycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hh_uz', models.PositiveIntegerField(default=0)),
                ('olx_uz', models.PositiveIntegerField(default=0)),
                ('telegram', models.PositiveIntegerField(default=0)),
                ('recommend', models.PositiveIntegerField(default=0)),
                ('total_dashboard', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
                'db_table': 'response',
            },
        ),
    ]
